config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_flat, only: %i[show edit update destroy]

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render :edit
    end
  end


  def destroy
    if @flat.destroy
      redirect_to flats_path
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :number_of_guests, :price_per_night)
  end

  def find_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/flats/_navbar.html.erb
<h1>Flats#create</h1>
<p>Find me in app/views/flats/create.html.erb</p>

app/views/flats/edit.html.erb
<div class="card p-4 rounded">
  <h1>Edit Flat</h1>
  <%= render "form", flat: @flat %>
</div>

app/views/flats/index.html.erb
<h1>All Flats</h1>
<p>All <%= @flats.count %> flats.</p>

<div class="row row-cols-1 row-cols-md-2 g-4">
  <% @flats.each do|flat| %>
    <div class="col">
      <div class="card h-100 shadow-sm bg-white rounded">
        <%= image_tag "https://source.unsplash.com/random?house?random_number=#{rand(100)}", class: "card-img-top" %>
        <div class="card-body">
          <h5 class="card-title"><%= flat.name %></h5>
          <p class="card-text"><%= flat.address %></p>

          <ul class="list-inline">
            <li class="list-inline-item"><i class="fas fa-user-friends"></i> <%= flat.number_of_guests %></li>
            <li class="list-inline-item"><i class="fas fa-euro-sign"></i> <%= flat.price_per_night %></li>
          </ul>

        </div>
        <div class="card-footer">
          <small class="text-muted">
            <ul class="list-inline mb-1">
              <li class="list-inline-item"><%= link_to "More Info", flat_path(flat), class: "link-primary" %></li>
              <li class="list-inline-item"><%= link_to "Edit", edit_flat_path(flat), class: "link-warning" %></li>
              <li class="list-inline-item"><%= link_to "Remove", flat_path(flat), method: :delete, class: "link-danger" %></li>
            </ul>
          </small>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<div class="card p-4 rounded">
  <h1>Add new flat</h1>
  <%= render 'form', flat: @flat %>
</div>

app/views/flats/show.html.erb
<div class="card p-4 mb-3 shadow-sm bg-white rounded">
  <h1><%= @flat.name %></h1>
  <h4><%= @flat.address %></h4>
</div>
<div class="card p-4 shadow-sm bg-white rounded">
  <h3>A bit more about this flat...</h3>
  <p><%= @flat.description %></p>
</div>
<div class="card p-4 shadow-sm bg-white rounded">
  <p><i class="fas fa-euro-sign"></i> <%= @flat.number_of_guests %></p>
  <p><i class="fas fa-user-friends"></i> <%= @flat.price_per_night %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container mt-4">
     <%= yield %>
    </div>
  </body>
</html>